# Autogenerated file
def render(plant_options, plant_type, days_planted, temperature, humidity, barometric_pressure, pico_internal_temp, thermistor_temp):
    yield """<!DOCTYPE html>
html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>Hydroponic Garden</title>
    <link rel=\"stylesheet\" href=\"/static/style.css\">
    <script src=\"https://kit.fontawesome.com/d2c60f03e4.js\" crossorigin=\"anonymous\"></script>
    <style>
        /* Add any additional styles here */
        .centered-table """
    yield """{
            margin: 0 auto;
            text-align: left;
            width: 50%;
        }

        .centered-table img """
    yield """{
            max-width: 100%;
            height: auto;
        }

        .sensor-status """
    yield """{
            list-style: none;
            padding: 0;
            margin-top: 10px;
        }

        .sensor-status li """
    yield """{
            margin-bottom: 10px;
        }
    </style>
</head>
<body>

"""
    if plant_type is None:
        yield """    <h2>Select Plant Type</h2>

    <div id=\"plant-options\">
        """
        for option in plant_options:
            yield """            <div class=\"plant-option\" onclick=\"selectOptionAndSubmit('"""
            yield str(option)
            yield """')\">
                <img src=\"/static/images/"""
            yield str(option.lower())
            yield """.jpg\" alt=\""""
            yield str(option)
            yield """\">
                <p>"""
            yield str(option)
            yield """</p>
            </div>
        """
        yield """    </div>

    <!-- For the '/submit' form -->
    <form id=\"start-form\" method=\"post\" action=\"/\" onsubmit=\"return validateAndRedirect(event)\">
        <input type=\"hidden\" id=\"selected-plant\" name=\"selected-plant\">
    </form>

    <hr class=\"separator\">

    <h2>Sensor Data</h2>
    <div class=\"sensor-data\">
        <!-- Your existing sensor data here -->
    </div>

"""
    else:
        yield """    <div class=\"centered-table\">
        <img src=\"/static/images/"""
        yield str(plant_type.lower())
        yield """.jpg\" alt=\""""
        yield str(plant_type)
        yield """\">
    </div>

    <div class=\"sensor-data centered-table\">
        <ul class=\"sensor-status\">
            <li><strong>Air Pump:</strong> <span id=\"air-pump-status\"></span></li>
            <li><strong>Water Pump:</strong> <span id=\"water-pump-status\"></span></li>
            <li><strong>Pico Temp:</strong> <span id=\"pico-temp\"></span></li>
        </ul>
    </div>

    <hr class=\"separator\">

    <h2>Sensor Data</h2>
    <div class=\"sensor-data\">
        <!-- Your existing sensor data here -->
    </div>

    <!-- For the '/reset' form -->
    <form method=\"post\" action=\"/\">
        <input type=\"submit\" name=\"reset_garden\" value=\"Reset Garden\">
    </form>

"""
    yield """
<script>
    function selectOptionAndSubmit(option) """
    yield """{
        // Set the selected plant in the hidden input field
        document.getElementById('selected-plant').value = option;
        
        // Submit the form
        document.getElementById('start-form').submit();
    }

    function validateAndRedirect(event) """
    yield """{
        // Add your validation logic here if needed
        // Return true to allow form submission or false to prevent it
        return true;
    }
</script>
</body>
</html>
"""
