# Autogenerated file
def render(plant_options, plant_type, days_planted, temperature, humidity, barometric_pressure, pico_internal_temp, thermistor_temp):
    yield """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>Hydroponic Garden</title>
    <link rel=\"stylesheet\" href=\"/static/style.css\">
    <script src=\"https://kit.fontawesome.com/d2c60f03e4.js\" crossorigin=\"anonymous\"></script>

</head>
<body>

"""
    if plant_type is None:
        yield """    <h2>Select Plant Type</h2>

    <div id=\"plant-options\">
        """
        for option in plant_options:
            yield """            <div class=\"plant-option\" onclick=\"selectOptionAndSubmit('"""
            yield str(option)
            yield """')\">
                <img src=\"/static/images/"""
            yield str(option.lower())
            yield """.jpg\" alt=\""""
            yield str(option)
            yield """\">
                <p>"""
            yield str(option)
            yield """</p>
            </div>
        """
        yield """    </div>

    <!-- For the '/submit' form -->
    <form id=\"start-form\" method=\"post\" action=\"/\" onsubmit=\"return validateAndRedirect(event)\">
        <input type=\"hidden\" id=\"selected-plant\" name=\"selected-plant\">
    </form>
    
   <hr class=\"separator\">
   
    <h2>Sensor Data</h2>
    <div class=\"sensor-data\">
            <div class=\"sensor-row\">
                <i class=\"fas fa-thermometer-half fa-2x\"></i>
                <p>Temperature: """
        yield str(temperature)
        yield """</p>
            </div>
            <div class=\"sensor-row\">
                <i class=\"fas fa-tint fa-2x\"></i>
                <p>Humidity: """
        yield str(humidity)
        yield """</p>
            </div>
            <div class=\"sensor-row\">
                <i class=\"fas fa-tachometer-alt fa-2x\"></i>
                <p>Barometric Pressure: """
        yield str(barometric_pressure)
        yield """</p>
            </div>
            <div class=\"sensor-row\">
                <i class=\"fas fa-microchip fa-2x\"></i>
                <p>Pico Internal Temperature: """
        yield str(pico_internal_temp)
        yield """</p>
            </div>
            <div class=\"sensor-row\">
                <i class=\"fas fa-thermometer fa-2x\"></i>
                <p>Thermistor Temperature: """
        yield str(thermistor_temp)
        yield """</p>
            </div>
        </div>
   

    </div>

"""
    else:
        yield """<div>
<h2>Hydro Garden</h2>
<div id=\"plant-options\">

            <div class=\"plant-option\">
                <img src=\"/static/images/"""
        yield str(plant_type.lower())
        yield """.jpg\" alt=\""""
        yield str(plant_type)
        yield """\">
                <p>"""
        yield str(plant_type)
        yield """</p>
            </div>
        
    </div>
<div class=\"sensor-data\">    
<div class=\"sensor-row\">
        <i class=\"far fa-calendar-alt fa-2x\"></i>
                <p>Days Planted: """
        yield str(days_planted)
        yield """</p>
        </div>
   </div>     
   <hr class=\"separator\">
   
    <h2>Sensor Data</h2>
    <div class=\"sensor-data\">
            <div class=\"sensor-row\">
                <i class=\"fas fa-thermometer-half fa-2x\"></i>
                <p>Temperature: """
        yield str(temperature)
        yield """</p>
            </div>
            <div class=\"sensor-row\">
                <i class=\"fas fa-tint fa-2x\"></i>
                <p>Humidity: """
        yield str(humidity)
        yield """</p>
            </div>
            <div class=\"sensor-row\">
                <i class=\"fas fa-tachometer-alt fa-2x\"></i>
                <p>Barometric Pressure: """
        yield str(barometric_pressure)
        yield """</p>
            </div>
            <div class=\"sensor-row\">
                <i class=\"fas fa-microchip fa-2x\"></i>
                <p>Pico Internal Temperature: """
        yield str(pico_internal_temp)
        yield """</p>
            </div>
            <div class=\"sensor-row\">
                <i class=\"fas fa-thermometer fa-2x\"></i>
                <p>Thermistor Temperature: """
        yield str(thermistor_temp)
        yield """ </p>
            </div>
        </div>
    


<!-- For the '/reset' form -->
<form method=\"post\" action=\"/\">
    <input type=\"submit\" name=\"reset_garden\" value=\"Reset Garden\">
</form>


</div>
"""
    yield """

<script>
    function selectOptionAndSubmit(option) """
    yield """{
        // Set the selected plant in the hidden input field
        document.getElementById('selected-plant').value = option;
        
        // Submit the form
        document.getElementById('start-form').submit();
    }

    function validateAndRedirect(event) """
    yield """{
        // Add your validation logic here if needed
        // Return true to allow form submission or false to prevent it
        return true;
    }
</script>
</body>"""
